import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS Nerd Font Mono" , style = "Regular" }
# normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
size = 12

[keyboard]
bindings = []
