import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.90
blur = true

[font]
# normal = { family = "MesloLGS Nerd Font", style = "Regular" }
# normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
# normal = { family = "Hasklug Nerd Font", style = "Regular" }
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12
offset = { x = 1, y = 0 }

[cursor]
style = { shape = "Block", blinking = "Never" }

[keyboard]
bindings = []
