import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.9
blur = true

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Regular" }
italic = { family = "MesloLGS Nerd Font", style = "Regular" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 12

[cursor]
style = { shape = "Block", blinking = "Never" }

[keyboard]
bindings = []
