import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.40
blur = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 12
offset = { x = 0, y = 2 }

[cursor]
style = { shape = "Block", blinking = "Never" }

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
