theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = false
cursorcolumn = false
color-modes = true
auto-completion = true
auto-save = false
auto-format = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = false

[editor.soft-wrap]
enable = true

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true

[editor.statusline]
left = [
  "mode",
  "file-name",
  "spinner",
  "file-modification-indicator",
  "read-only-indicator",
]
center = ["version-control"]
right = [
  "diagnostics",
  "register",
  "selections",
  "position",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
[keys.insert.j]
k = "normal_mode"
[keys.normal."space"]
x = ":buffer-close"
t = { i = ":toggle lsp.display-inlay-hints" }
